# Generated by Django 5.0.6 on 2025-09-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("predictor", "0003_communityreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityreport",
            name="commodity_category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="communityreport",
            name="county",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
